---
  - name: "Debian: Install required pagkages"
    apt:
      name: "{{ ls_debian_required_pkgs }}"
      state: present
      update_cache: yes
  - name: "Debian: Set java package name"
    set_fact:
      java_package: "{{ debian_java_package }}"
    when: java_package is undefined
  - name: "Debian: Install Java"
    apt:
      name: "{{ java_package }}"
      state: present
  # - name: Create required directories
  #   file:
  #       path: "{{ item }}" # required. Path to the file being managed.
  #       state: directory # not required. choices: absent;directory;file;hard;link;touch. If C(directory), all intermediate subdirectories will be created if they do not exist. Since Ansible 1.7 they will be created with the supplied permissions. If C(file), the file will NOT be created if it does not exist; see the C(touch) value or the M(copy) or M(template) module if you want that behavior.  If C(link), the symbolic link will be created or changed. Use C(hard) for hardlinks. If C(absent), directories will be recursively deleted, and files or symlinks will be unlinked. Note that C(absent) will not cause C(file) to fail if the C(path) does not exist as the state did not change. If C(touch) (new in 1.4), an empty file will be created if the C(path) does not exist, while an existing file or directory will receive updated file access and modification times (similar to the way `touch` works from the command line).
  #   loop:
  #     - "/etc/default/logstash"
  - name: "Debian: Add Elastic code signing key"
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
    when: ls_version is version('7.0', '>=')
  - name: "Debian: Add Elastic code repo"
    template:
      src: elastic-7.x.list.j2
      dest: /etc/apt/sources.list.d/elastic-7.x.list
    when: ls_version is version('7.0', '>=')
  - name: "Debian: Install package"
    apt:
      name: "logstash=1:{{ ls_version }}-1"
      state: present
      update_cache: yes
